#!/usr/bin/sh

basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
cd $basedir/AIP # It can be changed to $basedir/.../AIP but always keep /AIP at the end

#or

cd .../AIP

if [ $1 = "create" ]; then
    python3 scripts/create.py $2 $3
elif [ $1 = "remove" ]; then
    python3 scripts/remove.py $2 $3
elif [ $1 = "open" ]; then
    python3 scripts/open.py $2 $3
elif [ $1 = "settings" ]; then
    echo
    echo ">>> Opening settings"
    xdg-open settings.json
elif [ $1 = "source" ]; then
    echo
    echo ">>> Opening source code in VSCode"
    code .
elif [ $1 = "-v" ]; then
    echo "Version:" 
    python3 scripts/settings.py $1
elif [ $1 = "pf" ]; then
    python3 scripts/settings.py $1 $2 $3
elif [ $1 = "aip" ]; then
    xdg-open https://github.com/Smoqu/AIP
elif [ $1 = "repos" ]; then
    python3 -c "from scripts.gh import repos_get; repos_get()"
elif [ $1 = "gh" ]; then
    python3 -c "from scripts.settings import get_full_settings; print(get_full_settings()[2])"
elif [ $1 = "upgrade" ]; then
    python3 scripts/upgrade.py $1
elif [ $1 = "bu" ]; then
    python3 scripts/backup.py
elif [ $1 = "get-settings"]; then
    python3 scripts/get_settings_json.py
else
    echo
    echo 'Syntax:'
    echo    'aip <command>'
    echo    '<command>'
    echo        'Commands:'
    echo            '<create> <foldername> (<application>)'
    echo                '=> creates a folder inside the projects directory; once done opens it directly on your editor. (can also push on GitHub)'
    echo            '<remove> <foldername> (<application>)'
    echo                '=> removes a folder inside the projects directory; can also remove on GitHub.'
    echo            '<settings>'
    echo                'opens the settings in your editor'
    echo            '<source>'
    echo                'opens the source code in your editor'
    echo            '<-v>'
    echo                'the version of aip'
    echo            '<pf>'
    echo                'opens the main project folder'
    echo                '<-l>'
    echo                    'lists all your projects directories inside the main folder'
    echo                '<application> (<-l>)'
    echo                    "opens the application's folder"
    echo                '<aip>'
    echo                    'opens the AIP GitHub repository'
    echo                '<repos>'
    echo                    'lists all your repositories'
    echo                '<gh>'
    echo                    'lists all the applications unauthorized to push on GitHub'
    echo                '<upgrade>'
    echo
fi
